Major update - new features and documentation

diff --git a/groan b/groan
--- a/groan
+++ b/groan
@@ -1,26 +1,38 @@
-#!/bin/sh
+#!/bin/bash
 
 #Provide some basic features and
 #Redirect groan <cmd> to groan.<cmd>.cmd.sh
 
-#obtain the command requested
-command=$1
+# http://redsymbol.net/articles/unofficial-bash-strict-mode/
+set -euo pipefail
+IFS=$'\n\t'
+shopt -s nullglob # make sure globs are empty arrays if nothing is foound
 
-#shift the command from the arguments list
-shift
+# our contribution to help
+commonOptions="common options:
+--help    | -h | -?  Usage help for a command
+--quiet   | -q       Quiet mode - say nothing
+--verbose | -V       Verbose
+--debug   | -d | -D  Debug - tell all
+--dry-run            # default
+--confirm            # not a dry run - perform action
+"
 
 #default flags
 DEBUG=false
 VERBOSE=false
 LOUD=true
-DRYRUN=false
+DRYRUN=true
+CONFIRM=false
 SHOWHELP=false #exec command and only display the help metadata
 METADATAONLY=false #exec command only as far as the help metadata
 
-#search through the arguments for flags
-for arg in $@
+#search through the arguments for the command and flags
+args=()
+command=""
+for arg in "$@"
 do
-	case $arg in
+	case "$arg" in
 	  --debug | -d | -D)
 	    	DEBUG=true
 	    	VERBOSE=true
@@ -35,22 +47,37 @@ do
 	    	VERBOSE=true
 	    	LOUD=true
 	   ;;
-	  --quiet | -q)
+	   --quiet | -q)
 	    	LOUD=false
 	    	DEBUG=false
 	    	VERBOSE=false
 	    ;;
-	  --dry-run | -dry | --dry)
+	    --dry-run | -dry | --dry)
 	    	DRYRUN=true
+	    	CONFIRM=false
+	    ;;
+	    --confirm)
+	    	DRYRUN=false
+	    	CONFIRM=true
+	    ;;
+	    *)
+		if [[ "$command" = "" ]]; then
+		   command=$arg
+		else
+		   args+=($arg)
+		fi
 	    ;;
 	esac
+	shift
 done
 
 #find platform
+
 MACOSX=false
 WINDOWS=false
 UNIX=false
-system=`uname`
+system=$(uname)
+
 if [[  -d "/System/Library/Frameworks" ]] ; then
 	MACOSX=true
 elif [ -d "/WINDOWS" ] ; then
@@ -66,77 +93,74 @@ if [ -L "$scriptFile" ]; then
 fi
 scriptName=${scriptFile##*/} # `basename $scriptFile` 
 scriptDir=${scriptFile%/*} # `dirname $scriptFile`
-workingDir=`pwd`
+workingDir=$(pwd)
 searchablePath=":$PATH:"
 
-if [[ -z "$command" || "${command:0:1}" = "-" ]]; then
+$VERBOSE &&	echo "name:$scriptName		file:$scriptFile	dir:$scriptDir	"
+$VERBOSE && echo "command:$command		working:$workingDir" 		
+
+source "$scriptDir/$scriptName.locations"
+
+for configFile in ${configFileLocations[@]}
+do
+		$VERBOSE && echo "using configuration: $configFile"
+		source "$configFile"
+		break
+done
+
+# no command provided default to subcommmand help --help
+if [[ "$command" = "" ]]; then
 	echo
 	sh $scriptFile help --help
 	exit
 fi
 
-if $VERBOSE; then
-	echo "name:$scriptName		file:$scriptFile	dir:$scriptDir	"
-	echo "command:$command		working:$workingDir" 		
-fi
+target="$scriptName.${command}*.cmd.*"
 
-source "$scriptDir/$scriptName.locations.sh"
-
-for found in ${configlocations[@]}
-do
-	if [ -e "$found/.$scriptName.conf" ]; then
-		if $VERBOSE; then
-			echo "using configuration: $found/.$scriptName.conf"
-		fi
-		configFile="$found/.$scriptName.conf"
-		source "$configFile"
-		break
-	fi
-done
-
-target="$scriptName.${command}*.cmd.sh"
-
-previous="ok" 	
 count=0
-for loc in ${locations[@]}
+previous=""
+for loc in ${locations[@]} 
 do
+	[[ "$previous" == "$loc" ]] && break
+	previous="$loc"
+	
+	$DEBUG && echo "looking in: $loc"
+
 	for found in $loc/$target
 	do
-		if [[ -e "$found" && "$found" != "$previous" ]]; then
-			count=$((count + 1))	
-			if $DEBUG; then
-				echo "found #$count : $found"
-			fi
-			previous="$found"
-		fi
+		count=$((count + 1))	
+		$DEBUG && echo "found #$count : $found"
 	done
-done
 
-if [ $count -gt 1 ]; then
-	if $LOUD; then
-		echo "Warning: Command $command is ambiguous"
+	if [ $count -gt 1 ]; then
+		$LOUD && echo "Warning: Command '$command' is ambiguous (use --debug for more info)"
+		exit
 	fi
-	exit
-fi
 
-for loc in ${locations[@]}
-do
+	arg_str="${args[@]:+${args[@]}}" # needed bash<=4.1 when set -u is on
+	
 	for found in $loc/$target
 	do
-		if [ -e $found ]; then
-			if $DEBUG; then
-				echo "executing: $found"
-			fi
-			source "$found"
-			exit
-		fi
+		case ${found##*.} in
+			sh)
+				$DEBUG && echo "running source: $found $arg_str"
+				source "$found" "${args[@]:+${args[@]}}"
+			;;
+			exec)
+				$DEBUG && echo "running exec: $found $arg_str"
+				exec "$found" "${args[@]:+${args[@]}}"
+			;;
+			*)
+				$DEBUG && echo "running eval: $found $arg_str"
+				eval "$found" "${args[@]:+${args[@]}}"
+			;;
+		esac
+		exit
 	done
 done
 
-if $LOUD; then
-	echo "Warning: Command $command not found"
-	exit 1
-fi 
+$LOUD && echo "Warning: $scriptName sub-command $command not found"
+exit 1
 
 #"This Code is distributed subject to the MIT License, as in http://www.opensource.org/licenses/mit-license.php . 
 #Any additional contribution submitted for incorporation into or for distribution with this file shall be presumed subject to the same license."
