New release of core dispatching structure

diff --git a/groan/help/helper b/groan/help/helper
--- a/groan/help/helper
+++ b/groan/help/helper
@@ -94,7 +94,8 @@ if [ -L "$scriptFile" ]; then
 	scriptFile=`readlink -n $scriptFile`
 fi
 scriptName=${scriptFile##*/} # `basename $scriptFile` 
-breadcrumbs="$scriptName"
+breadcrumbs=("$scriptName")
+breadcrumbsStr=${breadcrumbs[*]// /|}
 scriptDir=${scriptFile%/*} # `dirname $scriptFile`
 configLocationsFile="$scriptDir/$configLocationsFileName"
 workingDir=$(pwd)
@@ -107,6 +108,15 @@ if $DEBUG; then
     echo "workingDir: $workingDir" 		
     echo "configLocationsFile: $configLocationsFile"
     echo "Command requested: '$command'"
+fi
+
+# handle the default empty case
+
+# no command provided default to subcommmand help --help
+if [[ "$command" = "" ]]; then
+	command="help"
+	SHOWHELP=true
+	METADATAONLY=true
 fi
 
 source "$configLocationsFile"
@@ -127,7 +137,76 @@ done
 
 dispatchLocations=("${locations[@]}")   
 
-source "$scriptFile-commands/dispatch-command.sh"
+####source "commands/dispatch-command.sh"
+# dispatcher for commands
+
+selfLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+$DEBUG && echo "dispatching-command: $scriptName selfLocation: $selfLocation"
+
+target="${command}*.cmd.*"
+exact="${command}.cmd.*"
+
+count=0
+previous=""
+for loc in ${dispatchLocations[@]} 
+do
+	[[ "$previous" == "$loc" ]] && continue
+	previous="$loc"
+	
+	$DEBUG && echo "Looking for $target in: $loc"
+
+	# if an exact match is available - upgrade the target to prioritise the exact match
+	for found in $loc/$exact
+	do
+		target=$exact
+	done
+
+	for found in $loc/$target
+	do
+		count=$((count + 1))	
+		$DEBUG && echo "Found #$count : $found"
+	done
+
+	if [ $count -gt 1 ]; then
+		$LOUD && echo "Warning: Command '$command' is ambiguous (use --debug for more info)"
+		exit
+	fi
+
+	arg_str="${args[@]:+${args[@]}}" # needed bash<=4.1 when set -u is on
+	
+	subcommandsLocation="$loc"
+	
+	for found in $loc/$target
+	do
+		case ${found##*.} in
+			sh)
+				$DEBUG && echo "Running source: $found $arg_str"
+				source "$found" "${args[@]:+${args[@]}}"
+				exit 0
+			;;
+			exec)
+				$DEBUG && echo "Running exec: $found $arg_str"
+				exec "$found" "${args[@]:+${args[@]}}"
+				exit 0
+			;;
+			*)
+				$DEBUG && echo "Extracting metadata from: $found"
+				$DEBUG && sed -n 's|^#m# \(.*\)$|\1|p' "$found"
+				
+				#evaluate meta-data first
+				eval "$(sed -n 's|^#m# \(.*\)$|\1|p' $found)"
+				
+				$DEBUG && echo "Running eval: $found $arg_str"				
+				eval "$found" "${args[@]:+${args[@]}}"
+			    exit 0
+			;;
+		esac
+		exit
+	done
+done
+
+$LOUD && echo "Warning: $scriptName $command : command  not found"
+exit 1
 
 # "This Code is distributed subject to the MIT License, as in http://www.opensource.org/licenses/mit-license.php . 
 # Any additional contribution submitted for incorporation into or for distribution with this file shall be presumed
